version: "3.7"
services:
  hello-world:
    image: ${DOCKER_ID:-ntdtfr}/hello-world:${IMAGE_VERION:-latest}
    build:
      context: .
    ports:
      - 5000:5000
    networks:
      - private
networks:
  private:
    driver: overlay
